---
name: "terraform-docs"

on:
  pull_request:
    types:
    - review_requested
    - ready_for_review

jobs:
  terraform-docs:
    uses: camptocamp/devops-stack/.github/workflows/modules-terraform-docs.yaml@main
